#!/bin/sh -l

sh -c "echo Hello world my name is $INPUT_MY_NAME"
sh -c $HOME 
sh -c $GITHUB_JOB 
sh -c $GITHUB_REF 
sh -c $GITHUB_SHA 
sh -c $GITHUB_REPOSITORY 
sh -c $GITHUB_REPOSITORY_OWNER 
sh -c $GITHUB_RUN_ID 
sh -c $GITHUB_RUN_NUMBER 
sh -c $GITHUB_RETENTION_DAYS 
sh -c $GITHUB_ACTOR 
sh -c $GITHUB_WORKFLOW 
sh -c $GITHUB_HEAD_REF 
sh -c $GITHUB_BASE_REF 
sh -c $GITHUB_EVENT_NAME 
sh -c $GITHUB_SERVER_URL 
sh -c $GITHUB_API_URL 
sh -c $GITHUB_GRAPHQL_URL 
sh -c $GITHUB_WORKSPACE 
sh -c $GITHUB_ACTION 
sh -c $GITHUB_EVENT_PATH 
sh -c $GITHUB_ACTION_REPOSITORY 
sh -c $GITHUB_ACTION_REF 
sh -c $GITHUB_PATH 
sh -c $GITHUB_ENV 
sh -c $RUNNER_OS 
sh -c $RUNNER_TOOL_CACHE 
sh -c $RUNNER_TEMP 
sh -c $RUNNER_WORKSPACE 
sh -c $ACTIONS_RUNTIME_URL 
sh -c $ACTIONS_RUNTIME_TOKEN 
sh -c $ACTIONS_CACHE_URL
